---
include:
  - board: eyelash_sofle_left
    shield: nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_left
  - board: eyelash_sofle_right
    shield: nice_view_adapter nice_view_gem
    artifact-name: eyelash_sofle_right
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: reset
